name: Portainer front build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  frontfile: 'front-public.tar.gz'
  node-version: '16.13.2'

jobs:
  build-front:
    runs-on: ubuntu-latest
        
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
          registry-url: https://registry.npmjs.org/
          
      - name: Install yarn 
        run: npm i -g yarn
       
      - name: Install dependencies
        run: yarn -i
      
      - name: Build front
        run: yarn run build:client

      - name: Packagin...
        run: tar -zcvf ${{ env.frontfile }} -C ./dist/ public
        
      - name: Read package.json
        id: version
        uses: tyankatsu0105/read-package-version-actions@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./build/linux/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            bigbugcc/portainer:latest
            bigbugcc/portainer:v${{ steps.version.outputs.version }}
        
      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Portainer front(CN) - v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          body: |
            Changes in this Release
            - å‰ç«¯è‹¥å¹²æ±‰åŒ–è¡¥å……   
            DockerHubğŸ¬   
            - [æŸ¥çœ‹](https://hub.docker.com/r/bigbugcc/portainer)
          files: |
            ${{ env.frontfile }}
            
